### ISSUE TITLE
Optimize bootstrap grid for mobiles 

### ISSUE THREAD

**Issue by quillcraftsman** [findsimilar/demo-front-end#3]
Optimize bootstrap grid for mobiles

**Comment by rakibulhaque9954** [comment]
I can do it

**Comment by quillcraftsman** [comment]
@rakibulhaque9954 , It will be great. This repository is a new part of big project. I will update README soon to easy start.

**Comment by quillcraftsman** [comment]
Done. @rakibulhaque9954 . You can start with:
[Project README](https://github.com/findsimilar/demo-front-end) and [Developer Guidelines](https://github.com/findsimilar/demo-front-end/blob/main/DEVELOPER_GUIDELINES.md)

**Comment by rakibulhaque9954** [comment]
your problem is the simple.html right?, index.html looks mobile responsive

**Comment by rakibulhaque9954** [comment]
![IMG_E8E6FD2637AF-1](https://github.com/findsimilar/demo-front-end/assets/131265804/44436ca6-26e2-455e-aba0-94eb7314b023)
I tried it on my phone

**Comment by quillcraftsman** [comment]
> your problem is the simple.html right?, index.html looks mobile responsive

Yes it is. It's a main functional page. More example will be there. It should work on many devices but now for desktops only.

**Comment by rakibulhaque9954** [comment]
I tried the use the find similar functionality, but it failed, anyway I should be able to add the bootstrap function soon

**Comment by rakibulhaque9954** [comment]
<img width="313" alt="Screenshot 2023-09-09 at 22 01 44" src="https://github.com/findsimilar/demo-front-end/assets/131265804/479cbc71-1160-4bcd-bf81-19efd3a25ae8">
do you want the response this way or you want the containers stacked one by one

**Comment by quillcraftsman** [comment]
> I tried the use the find similar functionality, but it failed, anyway I should be able to add the bootstrap function soon

It's normal, may be we will fix it later. Fetch failed because on production (http://demo.findsimilar.org) it uses production API but on localhost it tries to use localhost back-end server on 127.0.0.1:8000

You can:
* just ignore this (I think it's better way)
* up this project https://github.com/findsimilar/demo back-end server

**Comment by quillcraftsman** [comment]
> <img alt="Screenshot 2023-09-09 at 22 01 44" width="313" src="https://user-images.githubusercontent.com/131265804/266782160-479cbc71-1160-4bcd-bf81-19efd3a25ae8.png"> do you want the response this way or you want the containers stacked one by one

I think on desktops 3 in one row (like now). On smartphones I don't know. May be 3 in column or 2 in row and 1 below. If  it's exactly possible  May be there is a better option?

**Comment by rakibulhaque9954** [comment]
<img width="318" alt="Screenshot 2023-09-09 at 22 55 28" src="https://github.com/findsimilar/demo-front-end/assets/131265804/a746071d-70a3-4065-9b22-482949f31c9c">
changed
<img width="693" alt="Screenshot 2023-09-09 at 22 56 59" src="https://github.com/findsimilar/demo-front-end/assets/131265804/caf4b12e-739b-4276-ad44-d70e54619daf">

**Comment by quillcraftsman** [comment]
@rakibulhaque9954 , pull request has been merged.
 Looks great now. Thanks.
There is a problem with sticky footer now.
 I have created the new issue for it: https://github.com/findsimilar/demo-front-end/issues/5
