### ISSUE TITLE
Problems with sticky footer

### ISSUE THREAD

**Issue by quillcraftsman** [findsimilar/demo-front-end#5]
![image](https://github.com/findsimilar/demo-front-end/assets/135632271/6438f9db-b478-40a3-9d93-4794db2621c7)

This is the problem on mobile.
Footer is going up.

**Comment by rakibulhaque9954** [comment]
ill do it again by tomorrow, please assign me

**Comment by quillcraftsman** [comment]
> ill do it again by tomorrow, please assign me

Excellent. Assigned.

**Comment by rakibulhaque9954** [comment]
sorry one more thing, could you please provide me the dir and the file name, its much easier to navigate. Thanks.

**Comment by quillcraftsman** [comment]
> sorry one more thing, could you please provide me the dir and the file name, its much easier to navigate. Thanks.

Of course. Footer is in [/src/routes/+layout.svelte] https://github.com/findsimilar/demo-front-end/blob/main/src/routes/%2Blayout.svelte. It is the base template for the site structure.

To make it sticky I used `h-100` classes in several place and `mt-auto` in the footer

**Comment by rakibulhaque9954** [comment]
thanks

**Comment by rakibulhaque9954** [comment]
I updated it, please check it

**Comment by quillcraftsman** [comment]
@rakibulhaque9954 , I've merged the pull but have a same problem. http://demo.findsimilar.org/, And logo and GitHub picture go to center.

**Comment by quillcraftsman** [comment]
![image](https://github.com/findsimilar/demo-front-end/assets/135632271/e04f43ac-d05d-4781-8bf6-f7627988f4d4)

**Comment by rakibulhaque9954** [comment]
I see this could be due to previous simple page layout changes, thanks for the update will update surely by tomorrow

**Comment by quillcraftsman** [comment]
> I see this could be due to previous simple page layout changes, thanks for the update will update surely by tomorrow

Thanks. On this stage it's faster to push some little changes on production instead of run locally.

**Comment by rakibulhaque9954** [comment]
I am trying to debug it, its not working, the footer is always overlapping, the structure of the base could be an issue but having trouble debugging

**Comment by quillcraftsman** [comment]
> I am trying to debug it, its not working, the footer is always overlapping, the structure of the base could be an issue but having trouble debugging

@rakibulhaque9954 , sorry I missed this comment. What is the troubles debugging? Can you run development server with svelte?

**Comment by quillcraftsman** [comment]
I just deleted footer for a while.
