### ISSUE TITLE
Get examples from back-end

### ISSUE THREAD

**Issue by quillcraftsman** [findsimilar/demo-front-end#8]
Get example data and tutorials from back-end

**Comment by rakibulhaque9954** [comment]
so what basically are you looking for?

**Comment by quillcraftsman** [comment]
> so what basically are you looking for?

To fetch examples from back-end by API. Back-end part isn't ready yet.

**Comment by rakibulhaque9954** [comment]
so use Postgres or sql?

**Comment by quillcraftsman** [comment]
Back-end is already exists here: http://api.findsimilar.org. 
Front-end on http://demo.findsimilar.org use this api to find similar objects.

**Comment by quillcraftsman** [comment]
Back-end API is ready. In [swagger](http://api.findsimilar.org) endpoint /api/examples/<name>/ where `name` - example name
